# Using ML techniques to infer a multiplier

### Scenario

You discover that the number of apple seeds is directly tied to the overall height of the fruit, the seed count just needs to be multiplied by some fixed number. Create a model such that given the number of seeds, you can predict the height of the fruit. ***Use an iterative guessing approach to estimate the value of the multiplier.***

### We use two packages for this
1. random - to generate random numbers
2. numpy - this package handles matricies (or more technically arrays, which may have more dimensions than a matrix)

In [1]:
import numpy as np
import random

## Part 1 - Set up data

### Randomly select the multiplier
This will be the value the seed count is multiplied by, and the number we're trying to discover
* Select a random number between 10 and 100 (uniform distribution) and set it equal to a variable named "actual_multiplier"

In [5]:
actual_multiplier = random.uniform(10, 100)
print(actual_multiplier)

72.63593950456206


### Collect some apple seeds
Collect some samples of apple seeds, and measure the associated fruits
* To start we'll use 10 samples with different numbers of seeds in each sample. Here we'll use numbers 1, 2, ..., 9, 10
    * Make a numpy array named seed_count_array with these values
* For obvious reasons, we will not be measuring any apples right now. We're going to cheat a bit and say that the height of the associated apples were the number of seeds times our multiplier value plus noise
    * Make a numpy array called apple_height_array that is length 10, and equal to the seed_count_array times the actual_multiplier
    * Use the np.random.random method to create an array of length 10, and name it noise_array
    * Add the values from the elements of the noise array to the elements of apple_height_array
* Print out the actual_multiplier, seed_count_array, and apple_height_array

In [8]:
#Create an array with values 1-10
seed_count_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
seed_count_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
#Alt: Create an array with values 1-10
seed_count_array = np.arange(1,11)
seed_count_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
#Times the array by the random number
apple_height_array = seed_count_array * actual_multiplier
apple_height_array

array([ 72.6359395 , 145.27187901, 217.90781851, 290.54375802,
       363.17969752, 435.81563703, 508.45157653, 581.08751604,
       653.72345554, 726.35939505])

In [20]:
#Create the noise array
noise_array = np.random.random(10)
noise_array

array([0.38976799, 0.08382246, 0.81279041, 0.27069333, 0.75396983,
       0.1129841 , 0.91990327, 0.56817607, 0.37317437, 0.62496154])

In [22]:
#Add the noise values to the apple height values
apple_height_array = apple_height_array + noise_array
apple_height_array

array([ 73.41547549, 145.43952393, 219.53339933, 291.08514468,
       364.68763719, 436.04160522, 510.29138306, 582.22386818,
       654.46980429, 727.60931813])

In [23]:
#Print all values
print(actual_multiplier, seed_count_array, apple_height_array)

72.63593950456206 [ 1  2  3  4  5  6  7  8  9 10] [ 73.41547549 145.43952393 219.53339933 291.08514468 364.68763719
 436.04160522 510.29138306 582.22386818 654.46980429 727.60931813]


### Sidenote - How contrived is this exercise?

This is toy problem where we know the answer before we start. The point of this example is understand overall process of iterative improvement. Relationships typically being modelled with ML are more complicated than a simple multiplier, but suprisingly little changes for more complex problems. Here we're modelling a single parameter, but many models used in biology have 10s of millions, but are built out of many simple calculations like our exercise. The math is more advanced (but maybe not as much as you might think) and beyond our scope, but wouldn't serve much practical use anyway since these calculations are never ever done by hand, and a comprehensive understanding of them is not strictly necessary unless researching novel algorithm designs.

## Part 2 - Build out a training loop

### Steps (Add steps from slides here)
1. Write nested for loop to make a random prediction for each sample and go through 10 epochs
- Write a prediction function (named predict_multiplier) for this that guesses a value from -100 to 100
2. Write a function (calculate_loss) that substracts the prediction from the true value
- N.B. the multiplier is the parameter we are trying to guess, the prediction is the multilier times the number of seeds
- At each step print this loss, predicted multiplier, actual multiplier, predicted target, actual target and number of seeds
3. Create a variable that keeps track of the best (lowest) loss value - call it best_loss
- Make a list called best_param_list that appends *another* list of the loss, predicted multiplier, actual multiplier, predicted target, actual target and number of seeds (making a list of lists) whenever a new best loss if found
- Add a step before your loop to initialise these values
- Try increasing the number of epochs (make sure you comment out the print statements though!)
4. Update the predict function to take in the previous step's prediction and loss to make the output more accurate
- Add a step before your loop to initialise these values
5. 

In [160]:
#Define the predict_multiplier function that guesses a random multiplier between -100 to 100
def predict_multiplier(previous_prediction, previous_loss): 
    return previous_prediction+(previous_loss*0.001) 

In [161]:
#Define the function calculate_loss that substracts the prediction from the true_value
def calculate_loss(y_true, y_pred):
    return y_true - y_pred

In [171]:
#Create a for loop that iterates over the array
epoch_count = 10000
sample_count = len(seed_count_array)
best_loss = 100
best_param_list=[] #Create empty list to fill when best loss is found

predicted_multiplier = random.uniform(-100,100)
loss = calculate_loss(apple_height_array[0], predicted_multiplier*seed_count_array[0])

for i in range(epoch_count): #Iterate each epoch
    for j in range(sample_count): #Iterate each seed
        predicted_multiplier = predict_multiplier(predicted_multiplier, loss) #Predict the multipler (random no. between -100 to 100)
        loss = calculate_loss(apple_height_array[j], predicted_multiplier * seed_count_array[j]) #Calculate the loss, each of the actual apple heights minus the predicted apple heights
        #print(predict_multiplier, loss)
        if abs(loss) < best_loss:
            best_loss = abs(loss)
            best_param_list.append([loss, apple_height_prediction, actual_multiplier, 
                                    predicted_multiplier*seed_count_array[j], apple_height_array[j],
                                    seed_count_array[j]])
            
#If loss > 0, then prediction was too small
#If loss < 0, then prediction was too large
        
            

In [172]:
print('loss, predicted_multiplier, actual_multiplier, predicted_height, apple_height_array[j],seed_count_array[j]')
print()
for row in best_param_list[-10:-1]:
    print(row)

loss, predicted_multiplier, actual_multiplier, predicted_height, apple_height_array[j],seed_count_array[j]

[0.1424180768544261, -765.0686917542231, 72.63593950456206, 145.29710585438346, 145.4395239312379, 2]
[0.12840236467809518, -765.0686917542231, 72.63593950456206, 435.9132028585746, 436.0416052232527, 6]
[0.12466050179955346, -765.0686917542231, 72.63593950456206, 145.31486342943833, 145.4395239312379, 2]
[0.0758716834998836, -765.0686917542231, 72.63593950456206, 435.9657335397528, 436.0416052232527, 6]
[0.026161794478355205, -765.0686917542231, 72.63593950456206, 436.01544342877435, 436.0416052232527, 6]
[-0.020878773264144, -765.0686917542231, 72.63593950456206, 436.06248399651685, 436.0416052232527, 6]
[0.012954955289302461, -765.0686917542231, 72.63593950456206, 145.42656897594858, 145.4395239312379, 2]
[0.011906752770187268, -765.0686917542231, 72.63593950456206, 654.4578975375036, 654.4698042902738, 9]
[0.002149290046219221, -765.0686917542231, 72.63593950456206, 145.43737